config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
	get 'search' => 'search#index'
  
  # Routes that require authentication, redirected to devise
	authenticate :user do

  	resources :relations, only: [:create, :destroy]

  	resources :posts, only: [:create, :destroy]

	# route without argument of id for reading notifications of relations
  	patch "relations" => "relations#update"

  end

  devise_for :users

  get '(:username)' => 'home#index', as: 'user_timeline'

end

app/models/post.rb
include ActionView::Helpers::DateHelper

class Post < ActiveRecord::Base
  default_scope { order('created_at desc') }

  belongs_to :user, -> { select(:id,
  	:username
  )}

  validates :text, presence: true, length: { minimum: 3, maximum: 300 }

  def when
    time_ago_in_words created_at
  end

  def self.all_by_username(username)
    joins(:user).where(users: { username: username } )
  end

end

app/models/relation.rb
class Relation < ActiveRecord::Base
	belongs_to :user
	belongs_to :following, class_name: "User", foreign_key: :followed_id
	belongs_to :followed, class_name: "User", foreign_key: :follower_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :delete_all

  has_many :relations, foreign_key: :follower_id, class_name: "Relation", dependent: :delete_all
  has_many :relations_inverse, foreign_key: :followed_id, class_name: "Relation"

  has_many :following, through: :relations, source: :following
  has_many :followers, through: :relations_inverse, source: :followed

  after_initialize :set_default_values

  validates :username, presence: true, length: { minimum: 5, maximum: 10 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.search(query)
    where("username like ?", "%#{query}%").order("created_at DESC")
  end

  def set_default_values
    self.followers_check_timestamp = Time.now unless persisted?
  end

  def not_seen_new_followers
    followers.where('relations.created_at > ?', followers_check_timestamp)
  end

  def is_following(user)
    following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_in) << [:username]
     devise_parameter_sanitizer.for(:sign_up) << [:username]
     devise_parameter_sanitizer.for(:account_update)  << [:username]
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_filter :get_unread_notifications

  def get_unread_notifications

    # get the navbar notification count in all cases
    @new_followers = user_signed_in? ? current_user.not_seen_new_followers : Array.new

  end

end

app/controllers/home_controller.rb
class HomeController < BaseController
  before_action :timeline_setup, only: [:index]

  def index

    if params[:username] then

      # show the specified user timeline
      @timeline_user = User.find_by_username(params[:username])

      if @timeline_user then
        # get the specified user timeline
        @latest_posts = Post.all_by_username(params[:username]).page(params[:page])

        # if we are logged in check if the user is following
        @is_following = current_user.is_following(@timeline_user) if user_signed_in?

      else
        flash[:error] = t(:cant_find_user)
      end

    else

      # if not, just show our timeline
      # if the user is not logged in, and no user has been specified just show latest posts
      @latest_posts = (user_signed_in? ? Post.where("user_id IN (?) OR user_id = ?", current_user.following.select(:id), current_user.id) : Post.all).page(params[:page])

    end

  end

  def timeline_setup

    @post = Post.new
    @timeline_user = current_user

    #if params[:username] && @timeline_user then
    #  redirect_to root_path if @timeline_user.username == params[:username]
    #end

   end

end

app/controllers/posts_controller.rb
class PostsController < BaseController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_ownership, only: [:destroy]

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to root_path, notice: t(:post_success)
    else
      redirect_to root_path, notice: "#{t(:post_text)} #{@post.errors[:text].first}"
    end
  end

  def destroy
    @post.destroy
    #redirect_to :back, notice: t(:post_success_delete)
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back, notice: t(:post_success_delete)
    else
      redirect_to root_path, notice: t(:post_success_delete)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :text)
  end

  def check_ownership
    render status: 401 if @post.user != current_user and !current_user.try(:admin?)
  end

end

app/controllers/relations_controller.rb
class RelationsController < RestrictedAreaController

  def create

    # add a relation through the relations table
    @relation = current_user.relations.build(followed_id: params[:followed_id])

    if @relation.save then

      flash[:notice] = "#{t :following}#{@relation.following.username}"
      redirect_to user_timeline_path(@relation.following.username)

    else

      flash[:error] = t(:unable_to_follow)

    end

  end

  def destroy

    # destroy relation through the relations table
    @relation = current_user.relations.find_by_followed_id(params[:id])

    if @relation then

      @relation.destroy
      flash[:notice] = "#{t :unfollowing}#{@relation.following.username}"

    end

    redirect_to user_timeline_path(@relation.following.username)

  end

  # called by ajax, without id, just to update the seen timestamp
  def update
    current_user.followers_check_timestamp = Time.now
    current_user.save
    render nothing: true, status: 200, content_type: 'text/html'
  end

end

app/controllers/restricted_area_controller.rb
class RestrictedAreaController < BaseController
  before_action :authenticate_user!

  def authenticate_user
    user_signed_in?  
  end

end

app/controllers/search_controller.rb
class SearchController < RestrictedAreaController

  def index

    #unfortunately simple_form requires a model nesting for parameters
    if params[:user] then
      @users = User.search(params[:user][:username]).page(params[:page])
      @last_query = params[:user][:username];
    end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_profile_header.html.erb
<div class="row">
  <% if @timeline_user then %>
    <div class="col-md-2">
      <div class="text-center" style="padding-top:10px">
        <span class="label label-success"><%= @timeline_user.followers.count %> <%= t :followers %></span>
        <br/>
        <span class="label label-success">
          <%= "#{@timeline_user.following.count} #{t :user_is_following}" %>
        </span>
      </div>

    </div>
    <div class="col-md-2">
      <h2><%= @timeline_user.username %></h2>
      <% if user_signed_in? then %>
        <% if @timeline_user != current_user then %>
          <% if @is_following then %>
            <%= button_to relation_path(@timeline_user.id), method: :delete, data: { confirm: t(:confirmation) }, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"> <%= t :unfollow %></span>
            <% end %>
          <% else%>
            <%= button_to relations_path(followed_id: @timeline_user.id), method: :post, data: { confirm: t(:confirmation) }, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"> <%= t :follow %></span>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div style="clear:both" />
    <%= render partial: 'posts/form' %>
    <div style="clear:both" />
  <% end %>
</div>

app/views/home/_timeline.html.erb
<div style="clear:both"></div><br/><br/>

<% @latest_posts.each do |post| %>

<div class="row jumbotron">
  <div class="col-md-8 col-md-offset-2">
      <% if !user_signed_in? and !@timeline_user %>
        <!-- display avatar maybe? -->
      <% end %>
      <div class="col-md-10">
        <p><%= post.text %></p>
        <ul class="list-inline">
          <li>
            <%= link_to post.user.username, user_timeline_path(post.user.username) %> @ <%= post.when %> <%= t :ago %>
          </li>
        </ul>
      </div>
      <div class="col-md-1">
        <% if user_signed_in? and ((post.user.id == current_user.id) or current_user.try(:admin?)) then %>
          <%= button_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" do %>
            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

<% end %>

app/views/home/index.html.erb
<%= provide :title, t(:home_title) %>

<%= render partial: 'profile_header' %>

<div style="clear:both" />

<% if @latest_posts %>

  <% if @latest_posts.any? %>

    <% unless @timeline_user %>
      <h2><%= t :checkout_latest_posts %></h2>
    <% end %>
    
    <%= render partial: 'timeline' %>

    <div class="navbar-centered">
      <%= paginate @latest_posts, :theme => 'twitter-bootstrap-3' %>
    </div>

  <% elsif %>

    <br>
    <div class="row jumbotron" >
      <div class="col-md-12 text-center">
        <h4>
        <% if user_signed_in?%>
          <% if current_user == @timeline_user %>
            <%= t :no_posts %>
          <% else %>
            <%= t :no_posts_other_user, username: @timeline_user.username %>
          <% end %>
        <% else %>
          <%= t :no_posts_new_user %>
        <% end %>
        </h4>
      </div>
    </div>

  <% end %>
  
<% end %>

<% unless user_signed_in? %>

    <div class="row jumbotron" >
      <div class="col-md-12 text-center">
            
        <%= button_to new_user_session_path, method: :get, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"> <%= t :nav_login %></span>
        <% end %>

        <%= button_to new_user_registration_path, method: :get, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"> <%= t :nav_signup %></span>
        <% end %>

      </div>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-default navbar-fixed-top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand"><%= t :nav_home %></a>
        </div>

        <%= render partial: 'shared/nav' %>

      </div>
    </header>
    <div id="masthead">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h1><%= t :home_title %>
            <p class="lead"><%= t :home_subtitle %></p>
            </h1>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">

              <% if notice || alert then %>

                <div class="alert alert-info" role="alert">
                   <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                   <%= notice || alert %>
                </div>

              <% elsif flash[:error] then %>

                <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  <span class="sr-only">Error:</span>
                  <%= flash[:error] %>
                </div>

              <% end %>

              <%= yield %>

            </div>
          </div>
        </div>
      </div>
    </div>

    <footer>
          Made for my school project during RoR course at AMM VSU.
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<% if !params[:username] %>
	<div class="col-md-8 col-md-offset-2">

		<%= simple_form_for(@post) do |f| %>
		  <%= f.error_notification %>

		    <%= f.input :text, as: :text, label: "Post", maxlength: 300 %>
		    
		    <div class="pull-right">
		      <%= f.button :submit, class: "btn btn-primary", class: "btn btn-primary" %>
		    </div>

		<% end %>

	</div>
<% end %>

app/views/search/index.html.erb
<% provide:title, t(:search_users) %>

<%= simple_form_for :user, url: search_path, method: :get, html: {class: 'form-vertical' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :username, required: true, autofocus: true, input_html: { value: @last_query  } %>
  <div class="pull-right">
    <%= f.button :submit, "Search user", class: "btn btn-primary" %>
  </div>
<% end %>

<div style="clear:both" /><br/>


<% if @users.try(:empty?) %>

  <div class="row jumbotron">
    <div class="col-md-12 text-center ">
      <h4><%= t :no_result %></h4>
    </div>
  </div>

<% elsif @users %>

  <% @users.each do |user| %>

    <div class="row jumbotron">
      <div class="vcenter">
        <h2><%= link_to user.username, user_timeline_path(user.username) %></h2>
      </div>
    </div>

  <% end %>

  <div class="navbar-centered">
    <%= paginate @users, :theme => 'twitter-bootstrap-3' %>
  </div>

<% end %>

app/views/shared/_nav.html.erb
<nav class="collapse navbar-collapse" role="navigation">
  <% if user_signed_in? then %>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to t(:nav_users), search_path %>
      </li>
    </ul>
  <% end %>
  <ul class="nav navbar-right navbar-nav">
    <% unless user_signed_in? then %>
      <%- if controller_name != 'sessions' %>
        <li>
          <%= link_to t(:nav_login), new_user_session_path %>
        </li>
      <% end %>
      <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
        <li>
          <%= link_to t(:nav_signup), new_user_registration_path %>
        </li>
      <% end %>
    <% else %>
      <li>
        <%= render partial: 'shared/notification' %>
      </li>
      <li>
        <%= link_to t(:nav_account), edit_user_registration_path %>
      </li>
      <li>
        <%= link_to t(:nav_signout), destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_notification.html.erb
<% if @new_followers %>
  <div style="padding:5px">
  	<h4>

      <li class="dropdown">
        <a href="#" id="read-notifications" class="dropdown-toggle" data-toggle="dropdown">
          <span id="notification-icon" class="label label-<%= @new_followers.any? ? "danger" : "default" %>">
            <span class="glyphicon glyphicon-eye-open"></span>
            <span id="notification-count" ><%= @new_followers.length %></span>
          </span>
        </a>
        <ul class="dropdown-menu" style="padding:10px; max-height:300px; overflow:auto" >
        	<li class="center-inline">
            <% if @new_followers.any? %>
            	<h5><%= t :new_followers %></h5>
            <% else %>
              <h5><%= t :no_new_followers %></h5>
            <% end %>
        	</li>
        <% for new_follower in @new_followers do %>
        	<li>
  	        <%= link_to user_timeline_path(new_follower.username) do %>
  	        <%= new_follower.username %>
        		<% end %>
        	</li>
        <% end %>
        </ul>
      </li>
  	</h4>
  </div>
<% end %>